### PR TITLE
Storing datetimes as utc epoch

### PR DESCRIPTION
**Pull request by dhruv11**
#2 

There are 2 issues with this PR at the moment:
1) FinalFireTimeUtcSerializesCorrectly unit test fails as those times are now being stored as seconds since epoch, which means we no longer have millisecond precision. Therefore failures of the nature:

_Assert.Equal() Failure
      Expected: 2016-11-13T00:56:08.4226480+00:00
      Actual:   2016-11-13T00:56:08.0000000+00:00_

One way to overcome this would be to store milliseconds since epoch in dynamo and updating:
https://github.com/lukeryannetnz/quartznet-dynamodb/blob/master/src/QuartzNET-DynamoDB/DataModel/UnixEpochDateTimeExtensions.cs#L21

how do you think we should tackle this?

2) There is an issue with the unit test HolidayCalendarExcludedDays, which tests the serialization/deserialization of Excluded Dates in the Holiday Calendar.

This is due to the fact that storing datetimes as seconds since epoch means we lose the original timezone info associated with the DateTime object.

This leads to an assertion failure here
https://github.com/lukeryannetnz/quartznet-dynamodb/blob/master/src/QuartzNET-DynamoDB.Tests/Unit/CalendarSerialisationTests.cs#L123

as even though the expected date and the actual date are the same, one is of "Kind" local and the deserialized is of "Kind" UTC and the equality comparer isn't smart enough.

I've updated the unit test to only add dates of "Kind" UTC to the calendar as that is also what the quartz code seems to expect
https://github.com/quartznet/quartznet/blob/d3fe4060e323a5d87225119a540161f55f7b90d5/src/Quartz/Impl/Calendar/HolidayCalendar.cs#L205

Would you agree that updating the unit test was the right thing to do in this case?

(Note: PR build did not pick this up probably because local timezone for the build agent is UTC?)

@lukeryannetnz

### CODE REVIEW

**Comment by lukeryannetnz** [comment]
Overall the changes look good to me.

**Comment by lukeryannetnz** [comment]
Your reference to https://github.com/quartznet/quartznet/blob/d3fe4060e323a5d87225119a540161f55f7b90d5/src/Quartz/Impl/Calendar/HolidayCalendar.cs#L205 is valid, IMO the handling of timezones in .NET with the DateTime class is difficult. This is an example of why, the variable name includes "utc" and the comment clearly states that timezone will be ignored but they don't check the Kind, so the behaviour is unpredictable. 

I think ignoring timezone and assuming UTC is acceptable behaviour here. I agree, we should update the test. I would actually write a test that asserts the behaviour (create a non-utc datetime and expect to receive it back with date/time the same but no timezone) - to assert that this is by design. You could reference this discussion.

**Comment by lukeryannetnz** [comment]
Millisecond precision is interesting. It seems this is required by the quartz library:
https://github.com/quartznet/quartznet/blob/d3fe4060e323a5d87225119a540161f55f7b90d5/src/Quartz/Impl/Triggers/SimpleTriggerImpl.cs#L282

If we do this, it won't be unix time by definition https://en.wikipedia.org/wiki/Unix_time. That kind of annoys the purist in me, but whatever.

It's worth noting that I don't think this will fit in a 32-bit integer anymore. Dynamo supports "38 digits precision" (http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html) - is this enough?

**Comment by lukeryannetnz** [comment]
Final comment, this is a breaking DB change. Doesn't matter for now, but will be important post V1.

**Comment by dhruv11** [comment]
According to the docs the max Number data type in dynamo can handle is 9.9E+125, which is large enough to store milliseconds since epoch

However, as you mentioned milliseconds since epoch will not fit in an int anymore so I will need to change the datetimeConvertor and the datetimeOffsetConvertor to use doubles instead.

Also, as suggested I'll add the test case to assert DateTime objects are expected to be in UTC by design.

Would you like me to go ahead with the above mentioned changes or given we won't be able to switch over to storing the true Unix time (seconds since epoch) , do you see this change as moving from one custom representation to another (less readable) custom representation without much benefit, in which case I can close this PR.

@lukeryannetnz, let me know how you'd like me to proceed :)

**Comment by lukeryannetnz** [comment]
I *think* given that the quartz library requires millisecond precision, that we should store it. While milliseconds since epoch is a proprietary format, I think it's the best option we have. 

What do you think? 
Also sorry this took me a month to reply.

**Comment by dhruv11** [comment]
closing PR, see https://github.com/lukeryannetnz/quartznet-dynamodb/issues/2 for more info

**Pull request closed without merging**
